flask:
  server_host: 0.0.0.0
  server_port: 5000
  debug: false
  #用于存放运行过程中生成的有用的文件
  #output: flask_out
  logging_level: INFO
  log_dir: logs
  #每天一个文件
  log_when: H
  interval: 1
  #文件最大保存数,0表示不自动清除
  backupCount: 0
kibana:
  host: 127.0.0.1
  port: 5601
  #kibana中与es真实车流量数据建立的index名称,必须与es里的一致
  real_index_name: j xflask_realvolume
  #当real_index_name已经存在了，是否删除重建
  delete_real_index_if_exist: false
  #kibana中与es预测车流量数据建立的index名称，必须与es里的一致
  predict_index_name: jxflask_predictvolume
  #当predict_index_name已经存在了，是否删除重建
  delete_predict_index_if_exist: false
  map_name: jxflask_volume_visual
  map_title: 江西高速
  #当地图已经存在了，是否删除重建
  delete_map_if_exist: false
elasticsearch:
  host: 127.0.0.1
  port: 9200
  #es真实车流量数据存放的index名称
  real_index_name: jxflask_realvolume #jxflask_realvolume
  #当real_index_name已经存在了，是否删除重建
  delete_real_index_if_exist: false
  #es预测车流量数据存放的index名称
  predict_index_name: jxflask_predictvolume
  #当predict_index_name已经存在了，是否删除重建
  delete_predict_index_if_exist: false
  #存放收费记录的index
  row_records_index: test_01
  delete_row_records_index_if_exist: false
  #transform的id
  transform_id: jxtransform_realvolume
  #当transform已经存在了，是否删除重建
  delete_transform_if_exist: false
  #当transform的频率，生产环境是1h，取值范围只能是1s到1h
  transform_frequency: 30m
  transform_delay: 60s
  #es接受数据时，需要进行ingest timastamp存储
  pipeline_id: add_received
  delete_pipeline_if_exist: false
beam_pipline:
  pipeline_name: traffic_util
model:
  name: dcrnn
  use_gpu: true
  gpus: 1
  #由多少个线程节点并行计算
  intra_op_parallelism_threads: 5
  #由多少个线程进行调度
  inter_op_parallelism_threads: 5  
  keep_checkpoint_max: 10
  save_checkpoints_steps: 100
  #每30天对效果进行验证
  evaluate_interval: 30
  evaluate_metrics: MAPE
  #阈值
  evaluate_metrics_threshold: 0.3
  #应该满足的条件:evaluate_metrics<evaluate_metrics_threshold?
  evaluate_metrics_type: lower #  ##or higher
serving:
  models_dir: saved_model
  max_keep: 5
