@startuml
' left to right direction
top to bottom direction

frame DomainModel #lightblue
node source
node jmeter
node DataSplit
node Webflux #mediumpurple
database kafka
node Flink #pink
node ElasticSearch 
database IoTDB #grey
queue RabbitMQ #grey
node Ditto #lightgreen
node TrafficFlowPrediction

DomainModel -[plain]-> Flink   :Business Object Extracting
DomainModel --> Ditto   :Digital Twin Modeling
DataSplit --> jmeter    :station records
jmeter --> Webflux  :upload raw data

source --> Webflux      :Raw Message
Webflux --> kafka       :Produce Records

kafka --> Flink :consume records
Flink --> RabbitMQ      :Messages(Object Status)
Flink --> IoTDB         :Telemetry Measurements
Flink --> ElasticSearch :Gantry Records
ElasticSearch --> TrafficFlowPrediction :Gantry Historical Data
TrafficFlowPrediction -->ElasticSearch  :Gantry Forecast Data
RabbitMQ --> Ditto      :Messages(Object Status)
Ditto -[dotted]-> IoTDB :Telemetry Reference
@enduml

