@startuml

class 车辆
class Plate
class OBU
class CPC卡
class ETC卡
class 车道
class 收费站
class 门架
class 操作员
class 中心
class 分中心
abstract class 通行介质
abstract class 电子通行介质
class 车道程序
class 通行交易
class 通行记录
abstract class 站点记录

class 门架记录
abstract class 支付记录
class OBUETC支付记录
class 班次

class 发票记录
支付记录 <|-- OBUETC支付记录

通行记录 "1"*-- "1"  站点记录 : 入口记录
通行记录 "1"*-- "0..1" 站点记录 : 出口记录
通行记录 "1" *-- "*" 门架记录: 门架记录列表
通行记录 : 通行标识ID
通行记录 : 站点记录 入口记录
通行记录 : 站点记录 出口记录
通行记录 : 门架记录 [] 门架记录列表（m）
通行记录 : 通行介质 通行介质
通行记录 "1" *-- "1" 通行介质 : 通行介质

通行交易 : 通行标识ID
通行交易 : 交易描述
通行交易 : 通行记录 通行记录
通行交易 : 支付记录 支付记录

通行交易 "1" *-- "1" 支付记录 : 支付记录
通行交易 "1" *-- "1" 通行记录 : 通行记录



车辆 "1" o--"1" Plate:plate

车辆 : Plate 车牌
车辆 : int 车种
车辆 : int 车型
车辆 : 座位数
车辆 : 长
车辆 : 宽
车辆 : 高
车辆 : 核定载人数
车辆 : 轴组信息
车辆 : float 限载总重
车辆 : float 车辆重量
车辆 : 通行交易 [] 通行交易历史
车辆 : 通行交易 当前通行
车辆 : 车速（m）
车辆 : 最近经过门架/车站（m）

车辆 "1" o--"*" 通行交易 : 通行交易历史
车辆 "1" o--"1" 通行交易 : 当前通行




Plate :  int color
Plate : String number

操作员 : 工号
操作员 : 姓名


收费站 "1" o--"+" 车道 : 车道

收费站 : 站号
收费站 : HEX编码
收费站 : 站号（国际）
收费站 : 车道[] 车道
收费站 : 所属分中心
收费站 : 所属中心
收费站 : 经度
收费站 : 维度


车道 "1" *-- "1" 车道程序
车道 "1" *-- "1" 收费站 : 所属站

车道 : 车道类型
车道 : 车道程序
车道 : 车道号
车道 : 车道HEX编码
车道 : 车道号（国际）
车道 : 车道类型
车道 : 所属站

车道程序 : 版本号

收费站  ..> 分中心: 所属分中心
收费站  ..> 中心: 所属中心

门架 "0..1" -- "0..1" 门架: 对向门架
门架 : 门架编号
门架 : 控制器序号
门架 : 门架HEX值
门架 : 经度
门架 : 维度
门架 : 门架 对向门架

门架记录 : 是否拟合
门架记录 : 门架 门架
门架记录 : 电子通行介质 通行介质
门架记录 : 计费交易编号
门架记录 : 计费交易时间
门架记录 : 应收金额
门架记录 : 交易金额
门架记录 : 优惠金额
' 门架记录 : 识别的车型
' 门架记录 : TAC码
' 门架记录 : PSAM卡脱机交易序列号
' 门架记录 : 交易的服务类型
' 门架记录 : 算法标识
' 门架记录 : 消费密钥版本号
' 门架记录 : 天线ID编号
' 门架记录 : 计费模块版本号
' 门架记录 : 计费参数版本号
' 门架记录 : 交易耗时（单位：ms）
' 门架记录 : 通行状态（可省略）
' 门架记录 : 计费模块响应计费结果
' 门架记录 : 节假日状态
' 门架记录 : 交易结果
' 门架记录 : 特情类型
' 门架记录 : 匹配状态
' 门架记录 : 去重状态
' 门架记录 : 处理状态
' 门架记录 : 计费接口特情值
' 门架记录 : 收费特情类型
' 门架记录 : 是否修正过
' 门架记录 : 标签写入结果
' 门架记录 : 交易类型
' 门架记录 : 计费里程数
' 门架记录 : 本次计费拟合结果标识
门架记录 : 计费特情值组合
门架记录 : 更新过站信息结果
门架记录 : 收费单元处理标识
门架记录 "1" o-- "1" 门架: 门架
门架记录 "1" o-- "1" 电子通行介质 : 通行介质





通行介质 : int 介质类型
通行介质 : int 介质编码

通行介质 <|-- 电子通行介质
电子通行介质 <|-- CPC卡
电子通行介质 <|-- OBU
OBU "1" o-- "1" ETC卡
电子通行介质 "1" o-- "0..1" 车辆: 绑定车辆



OBU : 单/双片标识
OBU : 编号
OBU : 厂商编号
OBU : 序号编码
OBU : 版本号
OBU : OBU发行版本
OBU : 电量（m）

OBU : == EF01系统文件 ==
OBU : 发行方标识
OBU : 协约类型
OBU : 合同序列号
OBU : 合同签署日期
OBU : 合同过期日期
OBU : 拆卸状态（m）

OBU : == EF01车辆信息 ==
OBU : 车牌号
OBU : 车牌颜色
OBU : 车型
OBU : 车辆用户类型
OBU : 车辆尺寸
OBU : 车辆核定载质量/准牵引总质量
OBU : 整备质量
OBU : 车辆总质量
OBU : 核定载人数
OBU : 车辆识别代号
OBU : 车辆特征描述

' OBU : == EF02文件 ==
' OBU : 出入口时间（m）
' OBU : 路网编码（m）
' OBU : 收费站编码（m）
' OBU : 收费车道编码（m）
' OBU : 卡类型
' OBU : 卡号
' OBU : 车牌号
' OBU : 收费额（m）
' OBU : OBU的MAC地址

' OBU : == EF04交费信息文件==
' OBU : 同0019文件1-39字节
' OBU : 用户卡信息-写入 0015 文件第 1-20 字节
' OBU : 车辆用户类型（0015第41字节）
' OBU : 累计通行省份个数（m）
' OBU : 累计应收金额（m）
' OBU : 累计优惠金额（m）
' OBU : 累计交易成功次数（m）
' OBU : 累计计费里程（m）
' OBU : 标签无卡累计次数（m）
' OBU : 本省入口编码（m）
' OBU : 本省累计交易金额（m）
' OBU : 本省累计交易成功数量（m）
' OBU : 加密摘要
' OBU : 通行省份累计金额（m）



ETC卡 : == 0015文件 ==
ETC卡 : 发卡方标识
ETC卡 : 卡片类型
ETC卡 : 卡片版本号
ETC卡 : 卡片网络编号
ETC卡 : 用户卡内部编号
ETC卡 : 启用时间
ETC卡 : 到期时间
ETC卡 : 车牌号
ETC卡 : 车辆用户类型
ETC卡 : 车牌颜色
ETC卡 : 车型

' ETC卡 : == 0019联网收费复合消费 ==
' ETC卡 : 复合消费应用标识
' ETC卡 : 记录长度
' ETC卡 : 应用锁定标示
' ETC卡 : 入/出口收费网络号（m）
' ETC卡 : 入/出口收费站（m）
' ETC卡 : 入/出口车道编码（m）
' ETC卡 : 入/出口状态（m）
' ETC卡 : 入/出口时间（m）
' ETC卡 : 车型
' ETC卡 : ETC门架编号（m）
' ETC卡 : 通行门架时间（m）
' ETC卡 : 车牌号码
' ETC卡 : 车牌颜色
' ETC卡 : 车轴数（m）
' ETC卡 : 总重（m）
' ETC卡 : 车辆状态标识（m）
' ETC卡 : 一类交易累计金额

' ETC卡 : == 0018（终端交易记录） ==
' ETC卡 : 联机交易序号（m）
' ETC卡 : 透支金额（m）
' ETC卡 : 交易金额（m）
' ETC卡 : 交易类型标识（m）
' ETC卡 : 终端机编号（m）
' ETC卡 : 交易日期（m）
' ETC卡 : 交易时间（m）

' ETC卡 : == 0012（联网收费信息文件） ==
' ETC卡 : 入口收费路网号（m）
' ETC卡 : 入口收费站号（m）
' ETC卡 : 入口收费站号（m）
' ETC卡 : 入口时间（m）
' ETC卡 : 车型
' ETC卡 : 入出口状态（m）
' ETC卡 : 标识站 
' ETC卡 : 收费员工号（m）
' ETC卡 : 入口班次（m）
' ETC卡 : 车牌号码



CPC卡 : == EF01系统文件 ==
CPC卡 : CPC卡发行方标识
CPC卡 : CPC卡ID
CPC卡 : 版本号
CPC卡 : 合同签署日期
CPC卡 : 合同过期日期

CPC卡 : == EF02基本信息文件 ==
CPC卡 : CPC电量信息（m）
CPC卡 : 5.8GHz工作状态


CPC卡 : == EF01入出口信息 ==
CPC卡 : 车型
CPC卡 : 车牌号码
CPC卡 : 车牌颜色
CPC卡 : 入口收费路网号
CPC卡 : 入口收费站号
CPC卡 : 入口收费车道号
CPC卡 : 入口时间
CPC卡 : 5.8GHz工作状态控制
CPC卡 : 出入口状态
CPC卡 : 车种
CPC卡 : 入口收费员工号
CPC卡 : 入口班次
CPC卡 : 货车轴数
CPC卡 : 货车总重
CPC卡 : 核定载重
CPC卡 : 特殊货车信息

' CPC卡 : == EF02过站信息文件 ==
' CPC卡 : 已写入的有效过站信息总个数（m）
' CPC卡 : 已写入的最新ETC门架信息（m）
' CPC卡 : 过站信息（m）

' CPC卡 : == EF04过站信息文件 ==
' CPC卡 : 北京通行计费信息
' CPC卡 : 天津通行计费信息
' CPC卡 : ...
' CPC卡 : 澳门通行计费信息




班次 : 批次号
班次 : 操作员 收费员
班次 : 操作员 班长
班次 : 上班时间
班次 : 授权时间
班次 : 逻辑日期

班次 "1" *-- "1" 操作员: 收费员
班次 "1" *-- "1" 操作员 : 班长


站点记录 "1" *-- "1" 班次 : 记录班次
站点记录 "1" *-- "1" 车道 : 车辆经过车道
站点记录 "1" *-- "1" 车辆: 通行车辆

站点记录 : 交易流水号
站点记录 : 交易编码
站点记录 : 班次 记录班次
站点记录 : 压线圈时间
站点记录 : 车道 车辆经过车道
站点记录 : 站点时间（入口/出口）
站点记录 : 车牌识别记录 识别记录
站点记录 : 车辆 通行车辆
站点记录 : 车辆重量（入口/出口）
站点记录 : 车辆轴组（入口/出口）
站点记录 : 标记状态（入口/出口）
站点记录 : int 行驶方向
站点记录 : 过车速度
站点记录 : 按键数量
站点记录 : 按键信息

支付记录 : 支付类型
支付记录 : 卡面扣费金额
支付记录 : 交易类型
支付记录 : PSAM卡脱机交易序号
支付记录 : 终端机编号
支付记录 : 交易服务类型
支付记录 : 算法标识
支付记录 : 计费里程（米）
' 支付记录 : 实际里程（米）
' 支付记录 : 免费区间类型
' 支付记录 : 免费方式
' 支付记录 : 免费区域信息
' 支付记录 : 交易前余额（分）
' 支付记录 : 交易后余额（分）
' 支付记录 : 总交易金额
' 支付记录 : 优惠金额
' 支付记录 : 应收金额
' 支付记录 : 计费总里程数
' 支付记录 : 代收外省金额
' 支付记录 : 折扣优惠金额（分）
' 支付记录 : 卡成本金额（分）
' 支付记录 : 欠通行费金额（分）
' 支付记录 : 欠通行费标志
' 支付记录 : 欠卡成本金额（分）
' 支付记录 : 次票代收
' 支付记录 : 统缴金额
' 支付记录 : 应收通行费金额（分）
' 支付记录 : 通行费免收金额（分）
' 支付记录 : 本次最终支付通行费金额
' 支付记录 : 补费记录号
' 支付记录 : 支付卡类型
' 支付记录 : 支付卡网络号
' 支付记录 : 支付卡卡号 
' 支付记录 : 支付卡交易号
' 支付记录 : 第三方支付信息
' 支付记录 : 支付码
' 支付记录 : 折扣率（1‰）
' 支付记录 : 开票标识
' 支付记录 : 发票记录 发票信息


' 支付记录 : 参数版本组合
' 支付记录 : 省中心编号组合
' 支付记录 : 卡内门架编号组合
' 支付记录 : 收费单元数量
' 支付记录 : 收费单元组合
' 支付记录 : 收费单元时间组合
' 支付记录 : 收费单元实际收费金额组合
' 支付记录 : 收费单元优惠金额组合
' 支付记录 : 收费单元计费模块版本号组合
' 支付记录 : 收费单元计费参数版本号组合
' 支付记录 : 实收金额组合
' 支付记录 : 校验码
' 支付记录 : 收费路段编号组合
' 支付记录 : 公路类型

' 支付记录 : CPC卡省内累加金额
' 支付记录 : 最短路径交易金额
' 支付记录 : 最短计费里程
' 支付记录 : 交易金额占比
' 支付记录 : 实际计费方式
' 支付记录 : 计费模式
' 支付记录 : 费显显示信息
' 支付记录 : 最短路径计费参数版本号
' 支付记录 : 查验标志
' 支付记录 : 校检标志
' 支付记录 : 合法性验证通过的时间
' 支付记录 : 备注
' 支付记录 : 省中心优惠类型 
' 支付记录 : 省中心优惠金额 
' 支付记录 : 省中心优惠前交易金额 
' 支付记录 : 二次计费类型
' 支付记录 : 二次计费结果
' 支付记录 : 二次计费时间
' 支付记录 : 省中心二次计费前交易金额
' 支付记录 : 省中心二次计费优惠金额
' 支付记录 : 次票代收处理信息
' 支付记录 : 优免信息编号

OBUETC支付记录 : OBU应收金额
OBUETC支付记录 : OBU优惠金额
OBUETC支付记录 : OBU累计优惠前通行费金额
OBUETC支付记录 : OBU累计优惠后通行费金额
OBUETC支付记录 : OBU总交易成功次数
OBUETC支付记录 : OBU未插卡累计次数
OBUETC支付记录 : ETC卡累计交易金额
OBUETC支付记录 : 本省累计通行费金额
OBUETC支付记录 : 本省交易成功次数
OBUETC支付记录 : 多省交易信息组合


支付记录 "1" o-- "0..1" 发票记录:发票信息
发票记录 : 发票类型
发票记录 : 发票代码
发票记录 : 发票编号
发票记录 : 发票张数





@enduml