FROM adoptopenjdk/openjdk11:debian
MAINTAINER cz

ADD mymongo1.jar mymongo.jar




# FROM centos:7
# MAINTAINER cz

# WORKDIR /soft/jdk

# ADD jdk-11.0.13_linux-x64_bin.tar.gz /soft/jdk

# ADD mymongo1.jar mymongo.jar

# ENV JAVA_HOME=/soft/jdk/jdk-11.0.13
# ENV CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$HAVA_HOME/lib/tools.jar
# ENV PATH=$JAVA_HOME/bin:$PATH